// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var TezStats = require("../common/TezStats.js");
var MainLayout = require("../layouts/MainLayout.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var AccountOverview = require("../components/AccountOverview.js");

function Dashboard$Clicker(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var count = match[0];
  var match$1 = React.useState(function () {
        return /* Init */0;
      });
  var setData = match$1[1];
  var data = match$1[0];
  React.useEffect((function () {
          Curry._1(setData, (function (param) {
                  return /* Loading */1;
                }));
          var watchId = setTimeout((function (param) {
                  return Curry._1(setData, (function (param) {
                                return {
                                        TAG: /* Success */0,
                                        _0: "Found 123 (" + (String(count) + ")")
                                      };
                              }));
                }), Math.abs(Math.imul(1000, count)));
          return (function (param) {
                    clearTimeout(watchId);
                    
                  });
        }), [count]);
  var increase = function (evt) {
    evt.preventDefault();
    return Curry._1(setCount, (function (prev) {
                  return prev + 1 | 0;
                }));
  };
  var decrease = function (evt) {
    evt.preventDefault();
    return Curry._1(setCount, (function (prev) {
                  return prev - 1 | 0;
                }));
  };
  var dataElement;
  dataElement = typeof data === "number" ? "Loading..." : (
      data.TAG ? "Failed with " + data._0 : data._0
    );
  var buttonClass = "text-16 w-4 h-4 rounded bg-grey-10";
  return React.createElement("div", {
              className: "flex items-center justify-center bg-blue w-1/3 h-20"
            }, React.createElement("div", undefined, React.createElement("h2", undefined, dataElement)), React.createElement("div", undefined, React.createElement("button", {
                      className: buttonClass,
                      onClick: decrease
                    }, "-"), React.createElement("span", {
                      className: "w-8 font-bold text-36"
                    }, count), React.createElement("button", {
                      className: buttonClass,
                      onClick: increase
                    }, "+"), React.createElement("button", {
                      onClick: (function (_evt) {
                          return Curry._1(setCount, (function (param) {
                                        return 0;
                                      }));
                        })
                    }, "Reset")));
}

var Clicker = {
  make: Dashboard$Clicker
};

function Dashboard(Props) {
  var wallet = Props.wallet;
  var match = React.useState(function () {
        return /* Init */0;
      });
  var setState = match[1];
  var state = match[0];
  React.useEffect((function () {
          Curry._1(setState, (function (param) {
                  return /* Loading */1;
                }));
          var onDone = function (data) {
            return Curry._1(setState, (function (param) {
                          return {
                                  TAG: /* Success */0,
                                  _0: data
                                };
                        }));
          };
          var onError = function (code) {
            return Curry._1(setState, (function (param) {
                          return {
                                  TAG: /* Failed */1,
                                  _0: "Error code:" + String(code)
                                };
                        }));
          };
          return TezStats.Account.query(wallet.address, onDone, onError, undefined);
        }), [wallet.address]);
  var content;
  if (typeof state === "number") {
    content = React.createElement("div", undefined, "...");
  } else if (state.TAG) {
    content = React.createElement("div", undefined, state._0);
  } else {
    var account = state._0;
    var tmp = {
      name: wallet.name,
      address: account.address,
      balance: account.total_balance
    };
    if (wallet.avatar !== undefined) {
      tmp.avatar = Caml_option.valFromOption(wallet.avatar);
    }
    content = React.createElement(AccountOverview.make, tmp);
  }
  return React.createElement(MainLayout.make, {
              children: React.createElement("div", {
                    className: "w-full",
                    style: {
                      maxWidth: "34rem"
                    }
                  }, content)
            });
}

var make = Dashboard;

exports.Clicker = Clicker;
exports.make = make;
/* react Not a pure module */
