// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Page404(Props) {
  return React.createElement("div", undefined, "Page 404");
}

var make = Page404;

exports.make = make;
/* react Not a pure module */
