// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function TransactionPage(Props) {
  return React.createElement("div", undefined, "Transactions");
}

var make = TransactionPage;

exports.make = make;
/* react Not a pure module */
