// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Address = require("./Address.js");

function AccountOverview(Props) {
  var avatarOpt = Props.avatar;
  var name = Props.name;
  var address = Props.address;
  var balance = Props.balance;
  var avatar = avatarOpt !== undefined ? avatarOpt : "/static/img/default-avatar.png";
  var intl = new (Intl.NumberFormat)("en-US", {
        minimumFractionDigits: 2
      });
  var formattedBalance = intl.format(balance);
  return React.createElement("div", {
              className: "flex items-center bg-white rounded-lg px-6 py-8",
              style: {
                minWidth: "34rem"
              }
            }, React.createElement("img", {
                  className: "w-32 h-32 mr-3",
                  src: avatar
                }), React.createElement("div", {
                  className: "mt-4"
                }, React.createElement("div", {
                      className: "text-16 font-bold text-blue-90"
                    }, name + "'s wallet"), React.createElement(Address.make, {
                      address: address
                    }), React.createElement("div", {
                      className: "text-36 font-bold text-blue-90 mt-4"
                    }, formattedBalance + " ꜩ")));
}

var make = AccountOverview;

exports.make = make;
/* react Not a pure module */
