// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Link(Props) {
  var href = Props.href;
  var children = Props.children;
  return React.createElement("a", {
              className: "cursor-pointer",
              onClick: (function ($$event) {
                  console.log(href);
                  $$event.preventDefault();
                  
                })
            }, children);
}

var make = Link;

exports.make = make;
/* react Not a pure module */
