// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Route = require("../common/Route.js");
var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function Link(Props) {
  var route = Props.route;
  var children = Props.children;
  return React.createElement("a", {
              className: "cursor-pointer",
              onClick: (function ($$event) {
                  ReasonReactRouter.push(Route.toHref(route));
                  $$event.preventDefault();
                  
                })
            }, children);
}

var make = Link;

exports.make = make;
/* react Not a pure module */
