// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var App = require("./common/App.js");
var React = require("react");
var ReactDom = require("react-dom");

import './css/main.css'
;

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(App.make, {}), root);
}

/*  Not a pure module */
