// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Sidebar = require("../pages/Sidebar.js");
var Dashboard = require("../pages/Dashboard.js");
var ReactHotLoader = require("react-hot-loader");

var HotReloader = {};

function App(Props) {
  return React.createElement("span", {
              className: "flex"
            }, React.createElement(Sidebar.make, {}), React.createElement(Dashboard.make, {}));
}

var make = ReactHotLoader.hot(module)(App);

exports.HotReloader = HotReloader;
exports.make = make;
/* make Not a pure module */
