// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Icon$Clipboard(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("path", {
                  d: "M16 4h2a2 2 0 012 2v14a2 2 0 01-2 2H6a2 2 0 01-2-2V6a2 2 0 012-2h2"
                }), React.createElement("rect", {
                  height: "4",
                  width: "8",
                  rx: "1",
                  ry: "1",
                  x: "8",
                  y: "2"
                }));
}

var Clipboard = {
  make: Icon$Clipboard
};

function Icon$Copy(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("rect", {
                  height: "13",
                  width: "13",
                  rx: "2",
                  ry: "2",
                  x: "9",
                  y: "9"
                }), React.createElement("path", {
                  d: "M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"
                }));
}

var Copy = {
  make: Icon$Copy
};

function Icon$ArrowUp(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("path", {
                  d: "M12 19V5M5 12l7-7 7 7"
                }));
}

var ArrowUp = {
  make: Icon$ArrowUp
};

function Icon$VerticalDots(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              stroke: "currentColor",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("circle", {
                  cx: "12",
                  cy: "12",
                  r: "1"
                }), React.createElement("circle", {
                  cx: "12",
                  cy: "5",
                  r: "1"
                }), React.createElement("circle", {
                  cx: "12",
                  cy: "19",
                  r: "1"
                }));
}

var VerticalDots = {
  make: Icon$VerticalDots
};

exports.Clipboard = Clipboard;
exports.Copy = Copy;
exports.ArrowUp = ArrowUp;
exports.VerticalDots = VerticalDots;
/* react Not a pure module */
