// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Icon$ArrowUp(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("path", {
                  d: "M12 19V5M5 12l7-7 7 7"
                }));
}

var ArrowUp = {
  make: Icon$ArrowUp
};

function Icon$VerticalDots(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              stroke: "currentColor",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("circle", {
                  cx: "12",
                  cy: "12",
                  r: "1"
                }), React.createElement("circle", {
                  cx: "12",
                  cy: "5",
                  r: "1"
                }), React.createElement("circle", {
                  cx: "12",
                  cy: "19",
                  r: "1"
                }));
}

var VerticalDots = {
  make: Icon$VerticalDots
};

exports.ArrowUp = ArrowUp;
exports.VerticalDots = VerticalDots;
/* react Not a pure module */
