// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function fromAnchor(url) {
  switch (url) {
    case "" :
    case "dashboard" :
        return /* Dashboard */0;
    case "transactions" :
        return /* Transactions */1;
    default:
      return /* NotFound */2;
  }
}

function toHref(t) {
  switch (t) {
    case /* Dashboard */0 :
        return "#dashboard";
    case /* Transactions */1 :
        return "#transactions";
    case /* NotFound */2 :
        return "#page404";
    
  }
}

exports.fromAnchor = fromAnchor;
exports.toHref = toHref;
/* No side effect */
