// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var mockup_address2 = "tz1bDXD6nNSrebqmAnnKKwnX1QdePSMCj4MX";

var mockup_address = "tz1fvLppfweTwyfrW7WuqKVicVJkWB7bJV6y";

var bruno = {
  avatar: undefined,
  name: "Bruno",
  address: mockup_address
};

var steve = {
  avatar: undefined,
  name: "Steve",
  address: mockup_address2
};

var Stub = {
  mockup_address2: mockup_address2,
  mockup_address: mockup_address,
  bruno: bruno,
  steve: steve
};

function queryByAddress(address, onDone, onError, param) {
  var request = new XMLHttpRequest();
  request.open("GET", "https://api.tzstats.com/explorer/account/" + (address + "/operations"));
  request.addEventListener("load", (function (param) {
          var response = request.response;
          return Curry._1(onDone, JSON.parse(response));
        }));
  request.addEventListener("error", (function (param) {
          return Curry._1(onError, request.status);
        }));
  request.send();
  return function (param) {
    request.abort();
    
  };
}

var Transaction = {
  queryByAddress: queryByAddress
};

function query(address, onDone, onError, param) {
  var request = new XMLHttpRequest();
  request.open("GET", "https://api.tzstats.com/explorer/account/" + address);
  request.addEventListener("load", (function (param) {
          var response = request.response;
          return Curry._1(onDone, JSON.parse(response));
        }));
  request.addEventListener("error", (function (param) {
          return Curry._1(onError, request.status);
        }));
  request.send();
  return function (param) {
    request.abort();
    
  };
}

var Account = {
  query: query
};

var endpoint = "https://api.tzstats.com";

exports.endpoint = endpoint;
exports.Stub = Stub;
exports.Transaction = Transaction;
exports.Account = Account;
/* No side effect */
